name: Build
on:
  push:
    branches:
      - "*"
jobs:
  Build:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: "yarn"

      - name: Install dependencies
        run: |
          yarn --prefer-offline --immutable

      - name: Build
        run: |
          yarn build
