name: Deployment

on:
  push:
    tags:
      - v**

jobs:
  Deploy:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2

      - name: Mask secrets
        run: |
          echo "::add-mask::${{ secrets.REGISTRY_ADDRESS }}"

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: tle-visualizer
          tags: ${{ github.ref_name }}
          containerfiles: |
            ./Dockerfile

      - name: Push image to registry
        id: push-to-registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ secrets.REGISTRY_ADDRESS }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
