name: Deployment

on:
  push:
    tags:
      - v**

jobs:
  Deploy:
    runs-on: [self-hosted]
    steps:
      - name: Mask secrets
        run: |
          echo "::add-mask::${{ secrets.REGISTRY_ADDRESS }}"
      - name: Login to docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_ADDRESS }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.REGISTRY_ADDRESS }}/tle-visualizer:${{ github.ref_name }}
